name: Validate Plugins

on:
  pull_request:
    paths:
      - 'plugins/**'
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Build all plugins
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Upload build artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: plugin-builds
          path: dist/
          retention-days: 7
