name: Validate Skills

on:
  pull_request:
    paths:
      - 'skills/**'
  push:
    branches:
      - main
    paths:
      - 'skills/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Validate all skills
        run: |
          chmod +x scripts/validate.sh
          ./scripts/validate.sh

      - name: Build all skills
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Upload build artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: skill-builds
          path: dist/
          retention-days: 7
